"""Make project_id nullable

Revision ID: 3cb958af409f
Revises: 7dd4f106ff5e
Create Date: 2026-07-05 17:29:02.504908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cb958af409f'
down_revision: Union[str, Sequence[str], None] = '7dd4f106ff5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'project_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'project_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
